export enum ActionTypeKeys {
    GAME_START = "GAME_END",
    GAME_END = "GAME END",

    START_SELECT_PLAYERS = "START_SELECT_PLAYERS",

    START_GAME = "START_GAME",
    PLAYER_MOVE = "PLAYER_MOVE",

    START_ADD_PLAYER = "START_ADD_PLAYER",
    SAVE_ADD_PLAYER = "SAVE_ADD_PLAYER",
    CANCEL_ADD_PLAYER = "CANCEL_ADD_PLAYER",

    SET_EDIT_PLAYER = "SET_EDIT_PLAYER",
    FETCH_ALL_PLAYERS = "FETCH_ALL_PLAYERS",
    UPDATE_PLAYER = "UPDATE_PLAYER",
    EDIT_PLAYER = "EDIT_PLAYER",
    DELETE_PLAYER = "DELETE_PLAYER",

    OTHER_ACTION = "__any_other_action_type__"
}